name: TerritoryWars
version: '1.0.6'
main: com.alantaru.territorywars.TerritoryWars
api-version: '1.20'
depend: [SimpleClans, Vault]
softdepend: [dynmap]
description: Sistema de Guerra de Territórios integrado com SimpleClans

commands:
  tw:
    description: Comando principal do TerritoryWars
    usage: |
      §6=== TerritoryWars Comandos ===
      §e/tw create §f- Cria um território
      §e/tw info §f- Mostra informações do território
      §e/tw movecore §f- Move o núcleo
      §e/tw setname <nome> §f- Define nome do território
      §e/tw setdesc <desc> §f- Define descrição
      §e/tw setdisplayname <territoryName> <displayName> §f- Define o nome de exibição do território
      §e/tw setdescription <territoryName> <description> §f- Define a descrição do território
      §e/tw setbanner <url> §f- Define bandeira
      §e/tw mode <modo> §f- Define modo de proteção
      §e/tw reload §f- Recarrega o plugin
      §e/tw abandon §f- Abandona o territorio atual
      §e/tw exibir §f- Exibe a borda do territorio atual
      §e/tw list §f- Lista todos os territórios
      §e/tw clanlist <clanTag> §f- Lista todos os territórios de um clã

permissions:
  territorywars.*:
    description: Acesso a todos os comandos do TerritoryWars
    default: op
    children:
      territorywars.create: true
      territorywars.info: true
      territorywars.movecore: true
      territorywars.modify: true
      territorywars.mode: true
      territorywars.reload: true
      territorywars.abandon: true
      territorywars.rename: true
      territorywars.exibir: true
      territorywars.list: true

  territorywars.create:
    description: Permite criar territórios
    default: false
  
  territorywars.info:
    description: Permite ver informações de territórios
    default: true
  
  territorywars.movecore:
    description: Permite mover o núcleo do território
    default: false
  
  territorywars.modify:
    description: Permite modificar informações do território
    default: false
    children:
      territorywars.info: true
  
  territorywars.mode:
    description: Permite alterar o modo de proteção
    default: false
    children:
      territorywars.info: true
  
  territorywars.reload:
    description: Permite recarregar o plugin
    default: false
  
  territorywars.abandon:
    description: Permite abandonar territórios
    default: false

  territorywars.rename:
    description: Permite renomear territórios
    default: false
    
  territorywars.exibir:
    description: Permite exibir a borda do territorio
    default: op

  territorywars.list:
    description: Permite listar os territorios
    default: true

  territorywars.clanlist:
    description: Permite listar os territorios de um clã
    default: true