name: TerritoryWars
version: 1.0
main: com.alantaru.territorywars.TerritoryWars
author: Alantaru
api-version: 1.20
commands:
  territorywars:
    description: Main command for TerritoryWars plugin.
    usage: /territorywars
